# Generated by Django 3.1.7 on 2022-01-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20220106_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgroombooking',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
