# Generated by Django 3.1.7 on 2022-01-06 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0005_auto_20220106_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgroombooking',
            name='homes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerapp.post'),
        ),
        migrations.AlterField(
            model_name='pgroombooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
