# Generated by Django 3.1.7 on 2022-01-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_auto_20220106_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGRoombooking',
        ),
    ]
