# Generated by Django 3.1.7 on 2022-01-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ownerapp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0008_delete_pgroombooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
