# Generated by Django 3.1.7 on 2022-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_auto_20220209_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
